name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install and Build
      run: |
        npm ci
        npm run build
        
        # Add robots.txt to dist
        echo "User-agent: AdsBot-Google" > dist/robots.txt
        echo "Disallow: /" >> dist/robots.txt
        
        echo "Verifying robots.txt:"
        cat dist/robots.txt
        
        echo "All files in dist:"
        find dist -type f | head -10
    
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
